---
driver_plugin: vagrant
platforms:
- name: centos-6.4
  driver_config: 
    box: opscode-centos-6.4
    box_url:  https://opscode-vm.s3.amazonaws.com/vagrant/opscode_centos-6.4_provisionerless.box
    require_chef_omnibus: "11.4.4-2"
- name: ubuntu-12.04
  driver_config:
    box: opscode-ubuntu-12.04
    box_url: https://opscode-vm.s3.amazonaws.com/vagrant/opscode_ubuntu-12.04_provisionerless.box
    require_chef_omnibus: "11.4.4-2"

suites:
- name: default
  run_list:
# add solo search heere if you want search support in your suite
#   - recipe[chef-solo-search]
    - recipe[test_cook_skeleton]
  attributes: {}

clusters:
  default:
    - default
