---
driver_plugin: vagrant
# if you want to use chef-zero instead of solo-search
# uncomment this
#provisioner: chef_zero

platforms:
- name: centos-6.4_chef-11.4.4
  driver_config: 
    box: opscode-centos-6.4_chef-11.4.4
    box_url:  https://opscode-vm.s3.amazonaws.com/vagrant/opscode_centos-6.4_chef-11.4.4.box
- name: ubuntu-12.04_chef-11.4.4
  driver_config:
    box: opscode-ubuntu-12.04_chef-11.4.4
    box_url: https://opscode-vm.s3.amazonaws.com/vagrant/opscode_ubuntu-12.04_chef-11.4.4.box

suites:
- name: default
  run_list:
# add solo search here if you want search support in your suite
#   - recipe[chef-solo-search]
    - recipe[test_cook_skeleton]
  attributes: {}

clusters:
  default:
    - default
